CREATE PROCEDURE [dbo].[sp_insertOrUpdateTeacher]
	@FIRSTNAME nvarchar(50), 
	@LASTNAME nvarchar(50),
	@EMAIL nvarchar(50),
	@TEACHER_ID int
AS
IF (NOT EXISTS(SELECT 1 FROM Teacher WHERE FirstName=@FIRSTNAME AND LastName=@LASTNAME AND Email=@EMAIL) AND @TEACHER_ID = -1)
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Teacher (
	FirstName, LastName, Email) 
	VALUES (
	@FIRSTNAME, @LASTNAME, @EMAIL); 

	SELECT TeacherID=SCOPE_IDENTITY()
END
ELSE 
	UPDATE Teacher SET FirstName=@FIRSTNAME,LastName=@LASTNAME,Email=@EMAIL WHERE TeacherId = @TEACHER_ID;
	SELECT TeacherID FROM Teacher WHERE FirstName=@FIRSTNAME AND LastName=@LASTNAME AND Email=@EMAIL
GO
GO
