CREATE PROCEDURE [dbo].[sp_insertTest]
	@NAME nvarchar(50), 
	@TEACHER_ID int,
	@LECTURE_ID int
AS
IF NOT EXISTS(SELECT 1 FROM Test WHERE Name=@NAME AND TeacherID=@TEACHER_ID AND LectureID=@LECTURE_ID) 
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Test(Name, TeacherID, LectureID) 
			     VALUES (@NAME, @TEACHER_ID,@LECTURE_ID); 
	SELECT TestID=SCOPE_IDENTITY()
END
GO
