CREATE PROCEDURE [dbo].[sp_insertClass]
	@NAME nvarchar(20)
AS
IF NOT EXISTS(SELECT 1 FROM Class WHERE Name=@NAME) 
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Class(Name) 
			     VALUES (@NAME); 
	SELECT ClassID=SCOPE_IDENTITY()
END
ELSE SELECT ClassID FROM Class WHERE Name=@NAME
GO