version: '3'

services:
  dataservice:
    image: dataservice
    build:
      context: .
      dockerfile: DataService/Dockerfile

  begintest:
    image: begintest
    build:
      context: .
      dockerfile: ../BeginTest/Dockerfile


  authentication:
    image: authentication
    build:
      context: .
      dockerfile: Authentication/Dockerfile


  authdataservice:
    image: authdataservice
    build:
      context: .
      dockerfile: AuthDataService/Dockerfile


  studenttest:
    image: studenttest
    build:
      context: .
      dockerfile: ../StudentTest/Dockerfile

